### ISSUE TITLE
Posted twice, formatting messed up

### ISSUE THREAD

**Issue by Foggalong** [Timidger/autowikiabot-py#29]
In reply to [this comment](https://www.reddit.com/r/unixporn/comments/2tzz3j/suggest_me_a_terminal_font/co47iei) the bot messaged twice, and the formatting of the entire thing is messed up too.

**Comment by Timidger** [comment]
Thank you for the bug report, I have since fixed both issues. 

1) I was accidentally running two instances of the bot while messing around with init scripts, and have since disabled the init scripts

2) The formatting had messed up because autowikiabot, in preparation for the upcoming FCC net neutrality vote, has begun showing campaign ads to save the internet.

Regarding the last one, I realise not many people are as enthused about the upcoming vote despite how important it is, so I will remedy this action by presenting the actual image from the website alongside the loading blurb.
